joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

  
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint2
  gains:
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1